const ADMIN_HTML = `<!doctype html>
<html lang="vi"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#111827"><title>ChatGPT Gateway</title><style>:root{font-family:system-ui,-apple-system,sans-serif;color:#111827;background:#f3f4f6}*{box-sizing:border-box}body{margin:0;padding:18px}.app{max-width:520px;margin:auto}.card{background:#fff;border:1px solid #e5e7eb;border-radius:18px;padding:18px;margin-bottom:14px;box-shadow:0 4px 16px #0000000a}h1{margin:0 0 5px;font-size:24px}h2{font-size:17px;margin:0 0 10px}.muted{font-size:14px;color:#6b7280}.label{display:block;font-size:13px;font-weight:650;margin:14px 0 6px}input,button{width:100%;min-height:48px;border-radius:12px;font:inherit}input{border:1px solid #d1d5db;padding:12px}button{border:0;background:#111827;color:#fff;font-weight:650;padding:12px;margin-top:10px}button.secondary{background:#e5e7eb;color:#111827}.status{margin-top:12px;padding:12px;background:#f3f4f6;border-radius:12px;font-size:14px;white-space:pre-wrap}.code{margin-top:10px;padding:14px;background:#f9fafb;border-radius:12px;text-align:center;font-size:25px;font-weight:800;letter-spacing:2px}.hidden{display:none}.account{display:flex;justify-content:space-between;padding:11px 0;border-bottom:1px solid #eee}.account:last-child{border:0}.dot{display:inline-block;width:9px;height:9px;border-radius:50%;background:#16a34a;margin-right:7px}</style></head><body><main class="app"><section class="card"><h1>ChatGPT Gateway</h1><div class="muted">Quản lý ChatGPT bằng điện thoại</div></section><section class="card"><h2>Admin key</h2><div class="muted">Key chỉ lưu trong phiên trình duyệt.</div><label class="label" for="key">GATEWAY_ADMIN_KEY</label><input id="key" type="password" autocomplete="off" placeholder="Nhập admin key"><button id="save">Lưu key</button></section><section class="card"><h2>Đăng nhập ChatGPT</h2><button id="start">Bắt đầu đăng nhập</button><div id="status" class="status hidden"></div><div id="code" class="code hidden"></div><button id="open" class="secondary hidden">Mở trang đăng nhập</button></section><section class="card"><h2>Tài khoản</h2><button id="refresh" class="secondary">Làm mới</button><div id="accounts" class="status">Chưa tải.</div></section></main><script>
const keyInput=document.getElementById('key'),statusBox=document.getElementById('status'),codeBox=document.getElementById('code'),openButton=document.getElementById('open'),accountsBox=document.getElementById('accounts');
keyInput.value=sessionStorage.getItem('gateway_admin_key')||'';
const adminKey=()=>keyInput.value.trim();
function setStatus(value){statusBox.textContent=value;statusBox.classList.remove('hidden')}
async function api(path,options={}){const headers=new Headers(options.headers||{});headers.set('Authorization','Bearer '+adminKey());headers.set('Content-Type','application/json');const response=await fetch(path,{...options,headers});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body?.error?.message||'HTTP '+response.status);return body}
document.getElementById('save').onclick=()=>{sessionStorage.setItem('gateway_admin_key',adminKey());setStatus('Đã lưu key trong phiên hiện tại.')};
document.getElementById('start').onclick=async()=>{try{if(!adminKey())throw new Error('Nhập admin key trước.');const session=await api('/auth/device/start',{method:'POST'});codeBox.textContent=session.user_code;codeBox.classList.remove('hidden');openButton.classList.remove('hidden');openButton.onclick=()=>window.open(session.verification_url,'_blank','noopener');setStatus('Mở trang đăng nhập, nhập mã bên dưới. Sau khi xác nhận, giữ trang này mở để Gateway tự kiểm tra.');poll(session.login_id,session.interval_seconds||5)}catch(error){setStatus(error.message)}};
async function poll(loginId,interval){for(;;){await new Promise(resolve=>setTimeout(resolve,interval*1000));try{const result=await api('/auth/device/poll',{method:'POST',body:JSON.stringify({login_id:loginId,label:'mobile'})});if(result.status==='completed'){setStatus('Đăng nhập thành công.');await loadAccounts();return}if(result.status==='failed'||result.status==='expired'){setStatus('Phiên đăng nhập: '+result.status);return}setStatus('Đang chờ xác nhận đăng nhập…')}catch(error){setStatus(error.message);return}}}
async function loadAccounts(){try{const result=await api('/auth/accounts');if(!result.data?.length){accountsBox.textContent='Chưa có tài khoản.';return}accountsBox.innerHTML=result.data.map(account=>'<div class="account"><span><span class="dot"></span>'+escapeHtml(account.label||'account')+'</span><span>'+escapeHtml(account.status||'unknown')+'</span></div>').join('')}catch(error){accountsBox.textContent=error.message}}
function escapeHtml(value){return String(value).replace(/[&<>"']/g,character=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[character]))}
document.getElementById('refresh').onclick=loadAccounts;if(adminKey())loadAccounts();
</script></body></html>`;

export function renderAdminPage(): Response {
  return new Response(ADMIN_HTML, { headers: { "content-type": "text/html; charset=utf-8", "cache-control": "no-store" } });
}
