import { authenticateAdmin, ADMIN_SESSION_COOKIE, cleanupAdminSessions, isAdminSessionValid, revokeAdminSession } from "./admin-auth";
import { disableAccount, getChatGptToken, listAccounts, pollDeviceLogin, startDeviceLogin } from "./auth";
import { GatewayRequestError, UpstreamError } from "./errors";
import { createChatCompletionResponse, createImageEditResponse, createImageResponse, createResponsesResponse, diagnoseCodexUpstream } from "./providers";
import { probeResolveOverrides } from "./resolve-override";
import { probeWorkerTransports } from "./transport-debug";
import { probeCodexHosts } from "./codex-host-debug";
import { createRequestContext, enforceRateLimit, getUsageSummary, recordUsage } from "./observability";
import { validateChatRequest, validateImageEditRequest, validateImageGenerationRequest, validateResponsesRequest } from "./validation";
import type { Env } from "./types";
import { renderAdminPage } from "./admin-page";

const DEFAULT_CHAT_MODEL = "chatgpt-gpt-5.6";
const IMAGE_MODEL = "chatgpt-gpt-image-2";
const DEVICE_VERIFICATION_URL = "https://auth.openai.com/codex/device";
const API_RATE_LIMIT = 60;
const OPENAI_PROBE_URL = "https://api.openai.com/v1/models";
const CHATGPT_PROBE_URL = "https://chatgpt.com/robots.txt";

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    if (request.method === "OPTIONS") return new Response(null, { headers: corsHeaders() });
    const url = new URL(request.url);
    if (request.method === "GET" && url.pathname === "/health") return healthResponse(env);
    if (request.method === "GET" && (url.pathname === "/auth" || url.pathname === "/auth/")) return renderAdminPage();
    if (url.pathname.startsWith("/auth/")) return handleAuthRoute(request, env, url);
    if (!isAuthorized(request, env)) return errorResponse("authentication_error", "Invalid API key.", 401);
    if (request.method === "GET" && url.pathname === "/v1/models") return modelsResponse();
    if (request.method === "GET" && url.pathname === "/v1/usage") return json(await getUsageSummary(env));
    if (request.method === "GET" && url.pathname === "/v1/debug/upstream") return debugUpstreamResponse(env);
    if (request.method === "GET" && url.pathname === "/v1/debug/resolve-override") return debugResolveOverrideResponse(env);
    if (request.method === "GET" && url.pathname === "/v1/debug/transport") return json({ generated_at: new Date().toISOString(), runtime: "cloudflare-worker", checks: await probeWorkerTransports() });
    if (request.method === "GET" && url.pathname === "/v1/debug/network") return debugNetworkResponse(env);
    if (request.method === "GET" && url.pathname === "/v1/debug/codex-hosts") return json({ generated_at: new Date().toISOString(), runtime: "cloudflare-worker", checks: await probeCodexHosts() });
    if (request.method !== "POST") return errorResponse("invalid_request_error", "Method not allowed.", 405);
    return handleApiRequest(request, env, url);
  },
} satisfies ExportedHandler<Env>;

async function debugUpstreamResponse(env: Env): Promise<Response> { try { const token = await getChatGptToken(env); return json(await diagnoseCodexUpstream(env, token)); } catch (error) { return mapError(error); } }
async function debugResolveOverrideResponse(env: Env): Promise<Response> { try { const endpoint = new URL(env.CHATGPT_CODEX_ENDPOINT); return json({ generated_at: new Date().toISOString(), runtime: "cloudflare-worker", target_host: endpoint.hostname, checks: await probeResolveOverrides(endpoint.hostname) }); } catch (error) { return mapError(error); } }
async function debugNetworkResponse(env: Env): Promise<Response> { const checks = await Promise.all([probeNetworkEndpoint(CHATGPT_PROBE_URL), probeNetworkEndpoint(OPENAI_PROBE_URL)]); return json({ generated_at: new Date().toISOString(), runtime: "cloudflare-worker", checks }); }
async function probeNetworkEndpoint(url: string): Promise<Record<string, unknown>> { const response = await fetch(url, { method: "GET", redirect: "manual", cf: { cacheTtl: 0, cacheEverything: false }, headers: { Accept: "application/json, text/plain, */*", "User-Agent": "9Router/3 Codex-Compatible" } }); const body = await response.text(); return { url, status: response.status, ok: response.ok, content_type: response.headers.get("content-type"), cf_ray: response.headers.get("cf-ray"), server: response.headers.get("server"), location: response.headers.get("location"), body_prefix: body.slice(0, 160).replace(/\s+/gu, " ") }; }
async function healthResponse(env: Env): Promise<Response> { let databaseConfigured = false; try { await env.DB.prepare("SELECT 1").first(); databaseConfigured = true; } catch { databaseConfigured = false; } const diagnostics = { api_key_configured: Boolean(env.GATEWAY_API_KEY?.trim()), admin_credentials_configured: Boolean(env.ADMIN_USERNAME?.trim() && env.ADMIN_PASSWORD?.trim()), encryption_key_configured: Boolean(env.CHATGPT_TOKEN_ENCRYPTION_KEY?.trim()), database_configured: databaseConfigured }; return json({ ok: Object.values(diagnostics).every(Boolean), service: "chatgpt-gateway", diagnostics }, Object.values(diagnostics).every(Boolean) ? 200 : 503); }
async function handleApiRequest(request: Request, env: Env, url: URL): Promise<Response> { const context = createRequestContext(); const rateLimit = await enforceRateLimit(env, await hashClientKey(request), API_RATE_LIMIT); if (!rateLimit.allowed) return rateLimitResponse(rateLimit.resetAt); try { const payload: unknown = await request.json(); const token = await getChatGptToken(env); const response = await routeApiRequest(url.pathname, env, token, payload); await recordUsage(env, url.pathname, readModel(payload), response.status, Date.now() - context.startedAt, token.accountId); return withRateLimitHeaders(response, rateLimit.remaining, rateLimit.resetAt); } catch (error) { const response = mapError(error); await recordUsage(env, url.pathname, "unknown", response.status, Date.now() - context.startedAt); return withRateLimitHeaders(response, rateLimit.remaining, rateLimit.resetAt); } }
async function routeApiRequest(pathname: string, env: Env, token: Awaited<ReturnType<typeof getChatGptToken>>, payload: unknown): Promise<Response> { if (pathname === "/v1/chat/completions") return proxyResponse(await createChatCompletionResponse(env, token, validateChatRequest(payload))); if (pathname === "/v1/responses") return proxyResponse(await createResponsesResponse(env, token, validateResponsesRequest(payload))); if (pathname === "/v1/images/generations") return proxyResponse(await createImageResponse(env, token, validateImageGenerationRequest(payload))); if (pathname === "/v1/images/edits") return proxyResponse(await createImageEditResponse(env, token, validateImageEditRequest(payload))); throw new GatewayRequestError("Unknown endpoint."); }
async function handleAuthRoute(request: Request, env: Env, url: URL): Promise<Response> { if (request.method === "POST" && url.pathname === "/auth/login") return loginAdmin(request, env); if (request.method === "POST" && url.pathname === "/auth/logout") return logoutAdmin(request, env); if (request.method === "GET" && url.pathname === "/auth/me") return adminMe(request, env); if (request.method === "POST" && url.pathname === "/auth/api-key-check") return apiKeyCheck(request, env); const sessionValid = await isAdminSessionValid(env, readAdminSessionCookie(request)); if (!sessionValid) return errorResponse("authentication_error", "Admin login required.", 401); if (request.method === "POST" && url.pathname === "/auth/device/start") return startDeviceAuth(env); if (request.method === "POST" && url.pathname === "/auth/device/poll") return pollDeviceAuth(request, env); if (request.method === "GET" && url.pathname === "/auth/accounts") return json({ data: await listAccounts(env) }); if (request.method === "DELETE" && url.pathname.startsWith("/auth/accounts/")) { const accountId = url.pathname.split("/").pop(); if (!accountId) return errorResponse("invalid_request_error", "Account ID is required.", 400); await disableAccount(env, accountId); return json({ ok: true }); } return errorResponse("invalid_request_error", "Unknown authentication endpoint.", 404); }
async function apiKeyCheck(request: Request, env: Env): Promise<Response> { const sessionValid = await isAdminSessionValid(env, readAdminSessionCookie(request)); if (!sessionValid) return errorResponse("authentication_error", "Admin login required.", 401); try { const payload: unknown = await request.json(); if (!isRecord(payload) || typeof payload.api_key !== "string") return errorResponse("invalid_request_error", "api_key is required.", 400); const receivedKey = payload.api_key.trim(); const configuredKey = env.GATEWAY_API_KEY?.trim() ?? ""; const [receivedFingerprint, configuredFingerprint] = await Promise.all([fingerprint(receivedKey), fingerprint(configuredKey)]); return json({ match: Boolean(receivedKey && configuredKey && receivedKey === configuredKey), received_key_length: receivedKey.length, configured_key_length: configuredKey.length, received_key_sha256: receivedFingerprint, configured_key_sha256: configuredFingerprint }); } catch (error) { return mapError(error); } }
async function loginAdmin(request: Request, env: Env): Promise<Response> { try { const payload: unknown = await request.json(); if (!isRecord(payload) || typeof payload.username !== "string" || typeof payload.password !== "string") return errorResponse("invalid_request_error", "Username and password are required.", 400); const token = await authenticateAdmin(env, payload.username, payload.password); if (!token) return errorResponse("authentication_error", "Sai tài khoản hoặc mật khẩu.", 401); await cleanupAdminSessions(env); return json({ ok: true }, 200, sessionCookie(token)); } catch (error) { return mapError(error); } }
async function logoutAdmin(request: Request, env: Env): Promise<Response> { await revokeAdminSession(env, readAdminSessionCookie(request)); return json({ ok: true }, 200, expiredSessionCookie()); }
async function adminMe(request: Request, env: Env): Promise<Response> { return json({ authenticated: await isAdminSessionValid(env, readAdminSessionCookie(request)) }); }
function sessionCookie(token: string): Record<string, string> { return { "set-cookie": `${ADMIN_SESSION_COOKIE}=${token}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=43200` }; }
function expiredSessionCookie(): Record<string, string> { return { "set-cookie": `${ADMIN_SESSION_COOKIE}=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0` }; }
function readAdminSessionCookie(request: Request): string | null { const cookieHeader = request.headers.get("cookie") ?? ""; const match = cookieHeader.match(new RegExp(`(?:^|;\\s*)${ADMIN_SESSION_COOKIE}=([^;]+)`)); return match?.[1] ?? null; }
async function startDeviceAuth(env: Env): Promise<Response> { try { const session = await startDeviceLogin(env); return json({ login_id: session.id, verification_url: DEVICE_VERIFICATION_URL, user_code: session.userCode, interval_seconds: session.intervalSeconds, expires_at: session.expiresAt }); } catch (error) { return mapError(error); } }
async function pollDeviceAuth(request: Request, env: Env): Promise<Response> { try { const payload: unknown = await request.json(); if (!isRecord(payload) || typeof payload.login_id !== "string") return errorResponse("invalid_request_error", "login_id is required.", 400); const label = typeof payload.label === "string" ? payload.label : ""; const session = await pollDeviceLogin(env, payload.login_id, label); return json({ login_id: session.id, status: session.status }); } catch (error) { return mapError(error); } }
function isAuthorized(request: Request, env: Env): boolean { const authorization = request.headers.get("authorization") ?? ""; const bearer = authorization.match(/^Bearer\s+(.+)$/i)?.[1]?.trim(); const apiKey = bearer ?? request.headers.get("x-api-key")?.trim(); const configuredApiKey = env.GATEWAY_API_KEY?.trim(); return Boolean(apiKey && configuredApiKey && apiKey === configuredApiKey); }
async function fingerprint(value: string): Promise<string> { const digest = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(value)); return Array.from(new Uint8Array(digest), (byte) => byte.toString(16).padStart(2, "0")).join(""); }
async function proxyResponse(response: Response): Promise<Response> { const headers = new Headers(response.headers); for (const [key, value] of Object.entries(corsHeaders())) headers.set(key, value); headers.delete("content-length"); return new Response(response.body, { status: response.status, headers }); }
function modelsResponse(): Response { const created = Math.floor(Date.now() / 1000); return json({ object: "list", data: [{ id: DEFAULT_CHAT_MODEL, object: "model", created, owned_by: "openai-chatgpt" }, { id: IMAGE_MODEL, object: "model", created, owned_by: "openai-chatgpt" }] }); }
function mapError(error: unknown): Response { if (error instanceof GatewayRequestError) return errorResponse(error.type, error.message, error.status); if (error instanceof UpstreamError) return errorResponse(error.type, error.message, error.status); if (error instanceof SyntaxError) return errorResponse("invalid_request_error", "Request body must be valid JSON.", 400); const message = error instanceof Error ? error.message : "Unexpected gateway error."; return errorResponse("server_error", message, 500); }
function json(value: unknown, status = 200, extraHeaders: Record<string, string> = {}): Response { return new Response(JSON.stringify(value), { status, headers: { "content-type": "application/json; charset=utf-8", "cache-control": "no-store", ...corsHeaders(), ...extraHeaders } }); }
function errorResponse(type: string, message: string, status: number): Response { return json({ error: { type, message } }, status); }
function rateLimitResponse(resetAt: number): Response { return withRateLimitHeaders(errorResponse("rate_limit_error", "Rate limit exceeded.", 429), 0, resetAt); }
function withRateLimitHeaders(response: Response, remaining: number, resetAt: number): Response { const headers = new Headers(response.headers); headers.set("x-ratelimit-remaining", String(remaining)); headers.set("x-ratelimit-reset", String(Math.ceil(resetAt / 1000))); return new Response(response.body, { status: response.status, headers }); }
async function hashClientKey(request: Request): Promise<string> { const identity = request.headers.get("x-api-key") ?? request.headers.get("authorization") ?? request.headers.get("cf-connecting-ip") ?? "anonymous"; const digest = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(identity)); return Array.from(new Uint8Array(digest), (byte) => byte.toString(16).padStart(2, "0")).join("").slice(0, 32); }
function readModel(payload: unknown): string { return isRecord(payload) && typeof payload.model === "string" ? payload.model : "unknown"; }
function corsHeaders(): Record<string, string> { return { "access-control-allow-origin": "*", "access-control-allow-headers": "authorization, content-type, x-api-key", "access-control-allow-methods": "GET, POST, DELETE, OPTIONS" }; }
function isRecord(value: unknown): value is Record<string, unknown> { return typeof value === "object" && value !== null && !Array.isArray(value); }
